on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string (runs every day at 10:05 UTC = 9:05 (SVK))
    - cron:  "05 10 * * *"

name: Inflation_scheduler

jobs:
  run-r-script:
    runs-on: windows-latest
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}    
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with: 
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages:
            any::dplyr
            any::tidyr
            any::lubridate
            any::stringr
            any::ggplot2
            any::ggiraph
            any::htmlwidgets
            any::gt
            any::gtExtras
            any::purrr
            any::svglite
            #any::systemfonts

      - name: run-script
        run: Rscript main.R        
        
      - name: commit files
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m "Saving the results" || echo "no changes to commit"
          git push origin || echo "no changes to commit"
